packages:
  - packages/*
  - '!packages/.dashboard'
  - '!packages/.untracked'
onlyBuiltDependencies:
  - sqlite3
overrides:
  esbuild@<=0.24.2: '>=0.25.0'
  js-yaml@>=4.0.0 <4.1.1: '>=4.1.1'
  glob@>=10.2.0 <10.5.0: '>=10.5.0'
  valibot@>=0.31.0 <1.2.0: '>=1.2.0'
  systeminformation@<5.27.14: '>=5.27.14'
