// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ERC20Token$Type } from "./ERC20Token";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ERC20Token"]: ERC20Token$Type;
    ["contracts/ERC20Token.sol:ERC20Token"]: ERC20Token$Type;
  }

  interface ContractTypesMap {
    ["ERC20Token"]: GetContractReturnType<ERC20Token$Type["abi"]>;
    ["contracts/ERC20Token.sol:ERC20Token"]: GetContractReturnType<ERC20Token$Type["abi"]>;
  }
}
