/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface CounterInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "add"
      | "decrement"
      | "getCount"
      | "increment"
      | "reset"
      | "subtract"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "CountIncremented" | "CountReset"
  ): EventFragment;

  encodeFunctionData(functionFragment: "add", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "decrement", values?: undefined): string;
  encodeFunctionData(functionFragment: "getCount", values?: undefined): string;
  encodeFunctionData(functionFragment: "increment", values?: undefined): string;
  encodeFunctionData(functionFragment: "reset", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "subtract",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "add", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "decrement", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getCount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "increment", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "reset", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "subtract", data: BytesLike): Result;
}

export namespace CountIncrementedEvent {
  export type InputTuple = [newCount: BigNumberish, incrementer: AddressLike];
  export type OutputTuple = [newCount: bigint, incrementer: string];
  export interface OutputObject {
    newCount: bigint;
    incrementer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CountResetEvent {
  export type InputTuple = [resetter: AddressLike];
  export type OutputTuple = [resetter: string];
  export interface OutputObject {
    resetter: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Counter extends BaseContract {
  connect(runner?: ContractRunner | null): Counter;
  waitForDeployment(): Promise<this>;

  interface: CounterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  add: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  decrement: TypedContractMethod<[], [void], "nonpayable">;

  getCount: TypedContractMethod<[], [bigint], "view">;

  increment: TypedContractMethod<[], [void], "nonpayable">;

  reset: TypedContractMethod<[], [void], "nonpayable">;

  subtract: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "add"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "decrement"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "increment"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "reset"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "subtract"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "CountIncremented"
  ): TypedContractEvent<
    CountIncrementedEvent.InputTuple,
    CountIncrementedEvent.OutputTuple,
    CountIncrementedEvent.OutputObject
  >;
  getEvent(
    key: "CountReset"
  ): TypedContractEvent<
    CountResetEvent.InputTuple,
    CountResetEvent.OutputTuple,
    CountResetEvent.OutputObject
  >;

  filters: {
    "CountIncremented(uint256,address)": TypedContractEvent<
      CountIncrementedEvent.InputTuple,
      CountIncrementedEvent.OutputTuple,
      CountIncrementedEvent.OutputObject
    >;
    CountIncremented: TypedContractEvent<
      CountIncrementedEvent.InputTuple,
      CountIncrementedEvent.OutputTuple,
      CountIncrementedEvent.OutputObject
    >;

    "CountReset(address)": TypedContractEvent<
      CountResetEvent.InputTuple,
      CountResetEvent.OutputTuple,
      CountResetEvent.OutputObject
    >;
    CountReset: TypedContractEvent<
      CountResetEvent.InputTuple,
      CountResetEvent.OutputTuple,
      CountResetEvent.OutputObject
    >;
  };
}
